SpooderManEXE/Hacktoberfest2020-Expert

- Java Programs/tempConverter.java
> Create temperature convertor

- Python Programs/GuessTheNumber.py
Feeling Bored?? Don't worry, Play this game of Guessing the Number for free!!
> GuessTheNumber.py

- Python Programs/HangmanGame.py
Bored playing my other game?? (GuessingGame.py) Then here is a Brand New Hangman Game!!
> HangmanGame.py

- C Programs/patternPrinter.c
> Create pattern printer

- Python Programs/imdbscrapper.py
This is a Python built scrapper that scraps the movies details from IMDB official site contibuting to @hacktobefest-2020 always ready for open source contribution.
> IMDB Scrapper in Python

- Python Programs/DiceRoller.py
Imagine playing monopoly/any other board game (which uses dice) but you don't have a Dice with you!! Don't Worry here is a dice roller python script just for you!
> DiceRoller.py

- Python Programs/EmailFinder.py
I added an EmailFinder in python that finds all email addresses in your clipboard and copies the found email addresses to the clipboard.
> Added EmailFinder.py

- C++ Programs/KMP.cpp
- C++ Programs/MakingOfPreSuffixArray.cpp
KMP Algorithm in C++ for String
> Added KMP Algo for C++

- Python Programs/bring zeros to end.py
- Python Programs/bring_all_no_less_than_equal_to_k_together.py
- Python Programs/largest no of given digit.py
- Python Programs/min_no_of_swap.py
- Python Programs/rearrangement.py
- Python Programs/rearrangement_with_hashSet.py
- Python Programs/reversal.py
- Python Programs/reversing using loop and reverse fxn.py
Knowledge reference from "geeksforgeeks"
> Array Algorithms

- Python Programs/CRUD.py
- Python Programs/multiple3&5.py
- Python Programs/startriangle.py
- Python Programs/upsidedownstartriangle.py
added 4 new python script
python programs -->
CRUD.py
multiple3&5.py
startriangle.py
upsidedownstartriangle.py
Thank you :D
> python script

- Python Programs/exception.py
- Python Programs/scraping.py
create web scraping and simple exception
> added by dummytarget

- Python Programs/checkprime.py
Python program to check if the given number is prime or not
> checkprime.py

- C Programs/palindrome.c
> Palindrome.c

- C++ Programs/factorial.cpp
Calculate Factorial Using Recursion
> factorial.cpp

- Java Programs/amstrong_number.java
Check Armstrong Number for 3 digit number
> amstrong_number.java

- Python Programs/Longest Palindromic Substring.py
Longest Palindromic Substring problem
> Create Longest Palindromic Substring.py

- C++ Programs/Next larger element.cpp
- C++ Programs/Save-Gautham.cpp
- C++ Programs/Sort a  Stack.cpp
- C++ Programs/Stacksusingqueue.cpp
- C++ Programs/get minimum element from stack.cpp
- C++ Programs/maximimum-window-size.cpp
- C++ Programs/reversestring.cpp
- C++ Programs/smallest-number-left.cpp
Added Various Stacks Problems in C++
> Added Various C++ Programs

- Python Programs/dec_to_bin.py
- Python Programs/dec_to_hex.py
- Python Programs/dec_to_oct.py
For Hactoberfest 2020.
pls add label "hacktoberfest-accepted" if satisfied with my contribution.
> Added 3 programs

- Python Programs/Repeat_Check.py
Checking for any repetition in a string
> Repeat Checking

- C++ Programs/longest_subarray.cpp
please add this...Its my first pull request
> longest_subarray.cpp

- Java Programs/Graph.java
> Graph.java

- Python Programs/numbers_are_fun.py
Added a python based program which uses an api and prints a fun fact about numbers.
> added an api based number fact program

- Python Programs/graph.py
Also having algorithms:
- find shortest path
- find all paths
- determine a path between two nodes using backtracking
- find isolated nodes
- find vertex degree (also, min and max degree)
> Added Graph data structure implementation in Python

- Python Programs/divineDivisors.py
> Added files Divine Divisors

- Python Programs/BubbleSort.py
In this Bubble Sort technique the value get's sorted in lowest to largest order or you can say ascending order.
> BubbleSort.py

- C++ Programs/BinaryOccurrence.cpp
Added Binary Occurence CPP Implementation.
Peace ✌️
> Binary Occurence CPP Implementation

- README.md
The correct URL to check pull request progress is /profile not /stats. I've updated the README to reflect that
> Update README.md to correct progress FAQ

- Python Programs/Huffman_Coding.py
Implementation of Huffman Coding using Greedy Approach.
Huffman Coding is a technique of compressing data to reduce its size without loss of data. It is generally useful to compress the data in which there are frequently occurring characters.
It follows a Greedy approach since it deals with generating minimum length prefix-free binary codes.
It uses variable-length encoding scheme for assigning binary codes to characters depending on how frequently they occur in the given text.
Priority Queue is used for building the Huffman tree such that the character that occurs most frequently is assigned the smallest code and the one that occurs least frequently gets the largest code.
It follows this procedure: -
Create a leaf node for each character and build a min heap using all the nodes (The …
> Huffman_Coding.py

- Python Programs/CharacterCount.py
Its a program which counts the number of characters present in a string.
> Added a basic python program

- Python Programs/Quick Sorting 021.py
- Quick Sorting 021.py
> Hacktoberfest-2020

- Python Programs/Backtracking/Sudoko Solver using Backtracking.ipynb
- Python Programs/Backtracking/Sum of Subset problem using Backtracking.ipynb
Kindly review the code and merge the PR.
> Added some algos

- Python Programs/matrix-operations.py
Performs matrix operations on user input matrices
> Created Matrix-Operations.py

- Geography_quiz.py
> Geography_quiz.py

- C++ Programs/morris_preorder_traversal.cpp
Add morris preorder traversal for traversing a tree in O(1) space complexity.
Please review and merge the changes.
> Add morris traversal for preorder

- C Programs/powerSet.c
Power Set of a user-entered set.
> Added Power Set Program Code

- C Programs/circular_queue.c
- C Programs/stack.c
Added algorithms for stack and queue operations
> Data structures using C

- shut_down_your_computer _using _python.py
> shut_down_your_computer _using _python.py

- creating_message_box_using_python.py
this program will create a message box
> message_box_using_python.py

- Python Programs/Palindrome.ipynb
1.Checks whether given string is palindrome or not
2.Checks whether given number is palindrome or not
> Palindrome Program

- Python Programs/Operation_on_strings.ipynb
operations:
a) To display word with the longest length
b) To determines the frequency of occurrence of particular character in the string
c) To check whether given string is palindrome or not
d) To display index of first appearance of the substring
e) To count the occurrences of each word in a given string
> Program on Various operation on strings

- .idea/workspace.xml
- Python Programs/8ball.py
Added 8 ball game:
ask it a question and you'll get an answer!
> Added 8 ball game

- Find HCF of two numbers.py
> Find_HCF_of_two_numbers.py

- Area_of_triangle.py
> Area_of_triangle.py

- JavaScript/reverseInput.js
I added a function which returns the reverse of the input
> added reverse function in javascript

- Find LCM of two numbers
> Find LCM of two numbers.py

- Python Programs/pwdgen.py
It is a program that asks for password length and prints a strong password of same length for the user.
> password generator

- JavaScript/Data-types/LinkedList.js
- JavaScript/Data-types/Tree.js
I think the Data-types addition would contribute to javascript so i added that file and added a Tree data type as well. More data-types incoming
> Added a new Data-Types for javascript and added a Tree data type

- C Programs/Mark_Grade.c
Please do accept my Pull Request.
> Added two new C++ files

- Python Programs/Shuffle_deck_of_cards.py
Python program to shuffle a deck of cards!!
> Added Python program

- Python Programs/8ball.py
Put the if else block in while loop and added a choice in it.
> Done some changes in game

- Go/armstrong_number.go
- Go/factorial.go
- Go/fibonacci_series.go
- Go/pascal_triangle.go
- Go/simple_calculator.go
> #Hacktoberfest

- JavaScript/sortWithTimeout.js
JS has an in-built function for sorting. 
In this program, we are using the setTimeOut function for sorting our array.
> added sort with timeout program

- Haskell/Rewind.hs
This code reverses a list in haskell without using the in-built reverse function.
> added rewind - haskell

- Python Programs/Face-Detection-with-Opencv/Face-detection.py
- Python Programs/File_Read.py
Hey @SpooderManEXE,
I have created a folder named Face-Detection-with-OpenCv and also a file File_read.
This is my First Hacktoberfest, please mark it as hacktoberfest-accepeted.
Looking forward to it
> Added Face-detection and File_Read

- JavaScript/typewriter.html
I have added an HTML file that contains javascript code to show the text in typewriter effect.
> Added typewriter effect program

- C# Programs/QuickSort.cs
> Add quick sort algorithm

- Python Programs/alphabet_rangoli.py
Create a Rangoli of your own with alphabets
> Alphabet Rangoli

- C++ Programs/Friend_Function.cpp
> Friend_Function.cpp

- C Programs/PriorityQueue.c
It is a **data structure code**...topic named **Priority Queue**
**_We can add elements in any order by specifying the priority of the elements in queue_**
> Created PriorityQueue.c

- BYE pattern
Added a program to **print the pattern BYE** with _B Y and E_
> Created BYE pattern in C

- C Programs/alternate_fibo.c
Added a program to **print the alternate fibonacci** numbers _upto n terms_
> Created alternate_fibo.c

- Python Programs/File-Downloader.py
It is a file simple file downloader by url **YOU CAN DOWNLOAD PHOTOS,VIDEOS,FILES AND MANY MORE BY URL**
> Simple File Downloader

- Python Programs/MaximumEdgeofTriangle.py
- Python Programs/PerimeterOfRectangle.py
> add new file

- Python Programs/object_size.py
> Add object_size.py

- Java Programs/BinarySearch.java
Binary search with UpperBound and LowerBound implementation in java.
> Binary search implementation in java.

- Machine Learning/Uniform_Cost_Search.py
This algorithm is used as a base for the famous algorithm A* search which is based on heuristics and ucs, to find the optimal path in the graph, also a variant of Djkstra's Algorithm.
Hoping to merge for Hactoberfest-2020 !!
Also, mark hacktoberfest-2020 label if feasible, i am beginner to github.
> Added the Uniform Cost Search Algorithm of AI

- Python Programs/wordcount.py
the python scripts gives the frequency of words in a text file that the user enters.
> Added wordcount.py

- Python Programs/Roll a Dice.py
Contribution for Hacktoberfest
> Roll a Dice Game

- Python Programs/swap of two variables.py
> Update with pythonist style swap varible

- JavaScript/rgb_to_hex.js
This function receives an RGB value of color and converts it to a hex value of the color.
> rgbToHex converter

- Python Programs/DNSTracking_EthicalHacking/dns.py
- Python Programs/DNSTracking_EthicalHacking/readme.md
This folder contains a DNS tracker which can help you and your organization to track the IP address of the website to which your machine connects
This also provides a great opportunity for students who want to understand networks better.. this helps you see your packet travelling on the web as you search for websites
HAPPY HACKING AND STAY SAFE BY KNOWING YOUR WEAKNESSES
For hacktoberfest, please add hacktoberfest for easy recognization
> DNSTracking_EthicalHacking is a python code to visualize and see the IPs and the network connection

- C++ Programs/Sage's_Birthday(1419_D2_from_Codeforces).cpp
Please accept my pull request. Thank You.
> Added source code of 1419-D2 from Codeforces

- Python Programs/RockPaperScissorsSpockLizard.py
A simple rock, paper, scissors game in need of touchups
> Added a Python game

- Python Programs/Sketch_maker.py
Sketch maker using Canny Edge Detector
> HACKTOBERFEST: Sketch_maker.py

- Java Programs/Longest_Common_Subsequence.java
Added Longest Common Subsequence implementation in java.
> Longest Common Subsequence in java

- Python Programs/FindSizeOfaImage.py
Python Program to Find the Size (Resolution) of an Image. kindly accept my PR
> added Python Program to Find the Size (Resolution) of a Image

- Python Programs/Calculator/calculator.py
I have added a  simple calculator app in which you able to do functions like addition, subtraction, multiplication,division, etc.
please check it and accept my request.
Thank You
> Added calculator.py

- Python Programs/Age.py
This will be used to see young/teenager/old based on age and increment age as year passes.
> Created Age.py file

- Java Programs/SlidingWindow.java
Using arrays , deque and linkedlist
> Added SlidingWindow in java

- C++ Programs/Polymorphism.cpp
A program to illustrate polymorphism in the form of virtual functions in C++
> Added polymorphism.cpp 

- C Programs/tree_order_level_traversal.c
Contains the program for tree level order traversal
> tree_level_order_traversal

- Eval_Postfix.c
- bracket_balance.c
Hey there,please review and accept my PR.
Thank you.
> Added  Eval_Postfix.c and  bracket_balance.c

- Count the number of words in a string using hashmap.java
Program to count the number of word in a string using hashmap
> Create Count the number of words in a string using hashmap.java

- C++ Programs/flatten tree.cpp
A technique used for tree queries on path between two nodes or on subtree.
> flatten tree

- HTML/Image-Slider-FromScratch/img_slider.html
- HTML/Image-Slider-FromScratch/slider.css
- HTML/Image-Slider-FromScratch/slider.js
An **Html-CSS-JS Image Slider** with some Matured JS and Beautiful style.
> Html-Slider

- README.md
> Fixed some Typos in readme.md file

- HTML/Calculator.html
Hey i have just made a simple calculator in html.
> Simple calculator in html

- Check whether year is leap year or not.py
Program to check whether year is leap year or not.
> Create Check whether year is leap year or not.py

- JavaScript/Data-types/Queue.js
- JavaScript/Data-types/Stack.js
- Python Programs/Data Structures/Queue.py
- Python Programs/Data Structures/SingleLinkedList.py
- Python Programs/Data Structures/Stack.py
Adds basic implementation of Queue and Stack data structure in JavaScript and Python. Also adds an implementation of Singly Linked List in Python.
> Adds basic linear data structure in JavaScript and Python

- C++ Programs/manacher.cpp
Manacher's string matching algorithm implementation in cpp.
> added Manacher's algorithm implementation

- HTML/portfolio.html
Hi.I created a portfolio site using using HTML.
> created portfolio site

- C++ Programs/BitMasking.cpp
> BitMasking.cpp

- duplicates_in_array.py
elements that appear twice in an array
> Added Duplicates in an array

- C++ Programs/deque.cpp
> Dequeue all Operations and Functions

- C++ Programs/topological_sort.cpp
Created Topological Sorting Algorithm in C++ section
> Added Topological Sort

- C Programs/Amazing_Star_Patt.c
give input size minimum enough to see star pattern eg:- 25
>  Amazing_Star_Patt.c

- Python Programs/encryption.py
encryption algo for encrypting string with blake2b and diff SHA added
run python encryption.py
> encryption algo for encrypting string with blake2b and diff SHA added

- C Programs/circular que
C code for circular quee. it can hold upto 50 elements.
> Create circular que

- C Programs/tuple form of matrix
entered matrix converted into tuple form and do transpose.
> Create tuple form of matrix

- character count
you can change string and character to be searched by modifying code
> Create character count

- Java Programs/palindrome of word
you can change the word "malayalam". and it will work
> Create palindrome of word

- Java Programs/matrix multiplication 3x3
get multiplied matrix as final matrix
> Create matrix multiplication 3x3
